services:
    postgress:
        container_name: postgress_go
        image: postgres:16.4
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: qwerty
            PG_DATA: /data/postgres
        volumes:
            - ./postgres-data:/data/postgres
        ports:
            - '5432:5432'
